### 647. Palindromic Substrings

#### 雙指針

In [1]:
class Solution:
    def countSubstrings(self, s: str) -> int:
        n = len(s)
        res = n
        for i in range(n):
            print(f"{'-'*100}\ni = {i}")
            
            print("\n<< even >>") # "aa"
            even = self.find(s, n, left = i, right = i+1)
            print("\n<< odd >>") # "aba"
            odd = self.find(s, n, left = i, right = i+2)

            
            print(f"\nres = {res}, even = {even}, odd = {odd}")
            res += (even + odd)
            print(f"new: res = {res}")
        
        return res
        

    def find(self, s, n, left, right):
        count = 0
        while (left >= 0) and (right < n) and (s[left] == s[right]):
            print(f"((left={left}) >= 0) and  ((right={right}) < (n={n})) and ((s[left]=s[{left}]={s[left]}) == (s[right]=s[{right}]={s[right]}))")
            left -= 1
            right += 1
            count += 1
            print(f"count = {count}")
            
        return count

In [2]:
s = "aaa"
Solution().countSubstrings(s)

----------------------------------------------------------------------------------------------------
i = 0

<< even >>
((left=0) >= 0) and  ((right=1) < (n=3)) and ((s[left]=s[0]=a) == (s[right]=s[1]=a))
count = 1

<< odd >>
((left=0) >= 0) and  ((right=2) < (n=3)) and ((s[left]=s[0]=a) == (s[right]=s[2]=a))
count = 1

res = 3, even = 1, odd = 1
new: res = 5
----------------------------------------------------------------------------------------------------
i = 1

<< even >>
((left=1) >= 0) and  ((right=2) < (n=3)) and ((s[left]=s[1]=a) == (s[right]=s[2]=a))
count = 1

<< odd >>

res = 5, even = 1, odd = 0
new: res = 6
----------------------------------------------------------------------------------------------------
i = 2

<< even >>

<< odd >>

res = 6, even = 0, odd = 0
new: res = 6


6

#### 動態規劃

In [3]:
class Solution:
    def countSubstrings(self, s: str) -> int:
        import numpy as np

        n = len(s)
        dp = [[0] * n for _ in range(n)]
        for i in range(n):
            dp[i][i] = 1 # 單一字一定是回文，對角線為True
        print(f"orginal: dp = \n{np.array(dp)}")

        count = n
        for i in range(n-2, -1, -1):
            for j in range(i+1, n):
                print(f"\ni = {i}, j = {j}")
                if (s[i] == s[j]):
                    if ((j - i) == 1) or (dp[i+1][j-1]):
                        # (j - i) == 1, ex: "aa", "cc", 間隔為1，前後相同的字一定為回文
                        # dp[i+1][j-1],ex: "aba", "cdc"
                        print(f"( (s[i] = {s[i]}) == (s[j] = {s[j]}) ) and ( ((j - i = {j - i}) == 1) or (dp[i+1][j-1] = {dp[i+1][j-1]}) )")
                        dp[i][j] = 1
                        print(f"new: dp = \n{np.array(dp)}")
                    else:
                        print(f"only - ( (s[i] = {s[i]}) == (s[j] = {s[j]})")
                else:
                    print(f"(s[i] = {s[i]}) != (s[j] = {s[j]})")
                
                if dp[i][j]:
                    count += 1
                    print(f"count = {count}")
                    
        return count

In [4]:
s = "aaa"
Solution().countSubstrings(s)

orginal: dp = 
[[1 0 0]
 [0 1 0]
 [0 0 1]]

i = 1, j = 2
( (s[i] = a) == (s[j] = a) ) and ( ((j - i = 1) == 1) or (dp[i+1][j-1] = 0) )
new: dp = 
[[1 0 0]
 [0 1 1]
 [0 0 1]]
count = 4

i = 0, j = 1
( (s[i] = a) == (s[j] = a) ) and ( ((j - i = 1) == 1) or (dp[i+1][j-1] = 0) )
new: dp = 
[[1 1 0]
 [0 1 1]
 [0 0 1]]
count = 5

i = 0, j = 2
( (s[i] = a) == (s[j] = a) ) and ( ((j - i = 2) == 1) or (dp[i+1][j-1] = 1) )
new: dp = 
[[1 1 1]
 [0 1 1]
 [0 0 1]]
count = 6


6